# Site settings
title: Asheville Printmakers
email: your-email@domain.com
baseurl: https://clayh53.github.io/avl_printmakers
description: "Asheville Printmakers are an energetic group of artists expressing ideas through the medium of the print."

collections:
  blackbird-show:
    output: true


# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f4f4f4 #80B3FF
  secondary: c7c2ba #2c3e50 #FD6E8A
  secondary-dark: b5b1aa #A2122F

# Footer settings
footer:
  copyright: Asheville Printmakers
  location: Our location 
  social: we're social!
  credits: random fact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/avl_printmakers
  - title: facebook
    url: https://www.facebook.com/groups/1482129858744150/
  
# Postal address (add as many lines as necessary)
address:
  - line: Asheville &
  - line: Western North Carolina

# Credits content
credits: 'site hosted by Github pages'

# Build settings
markdown: kramdown
permalink: pretty

# Online resource links

resources:
  - title: "McClain's Printmaking Supplies"
    description: 'Supplies and tools for relief printmaking'
    url: http://www.imcclains.com
  - title: 'Graphic Chemical & Ink Co.'
    description: 'Supplies and tools for all types of printing'
    url: http://www.graphicchemical.com
  - title: "Conrad Machine Co."
    description: 'Fine Art Etching, Monotype, Combination and Lithography Presses and printmaking supplies'
    url: http://www.conradmachine.com    
  - title: "Takach Press"
    description: 'Fine Art Printing Presses, Print Studio Equipment and printmaking supplies'
    url: http://www.takachpress.com        
  - title: Art Boards
    description: 'Source for woodblocks for wood engraving'
    url: http://www.art-boards.com
  - title: Hiromi Paper
    description: 'Source for Japanese and other Asian paper and supplies'
    url: http://store.hiromipaper.com 
  - title: New York Central Art Supply
    description: 'Complete Art supply resource'
    url: http://www.nycentralart.com
  - title: Cape Fear Press
    description: 'Source for some specialized etching supplies. US source for Phoenix photogravure tissue and Izote etching inks'
    url: http://www.capefearpress.com/order.html           
  - title: Jerry's Artarama
    description: 'Comprehensive online source for discounted art supplies'
    url: http://www.jerrysartarama.com
