# Site settings
title: Asheville Printmakers
email: your-email@domain.com
baseurl: https://clayh53.github.io/avl_printmakers
description: "Asheville Printmakers are an energetic group of artists expressing ideas through the medium of the print."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f4f4f4 #80B3FF
  secondary: c7c2ba #2c3e50 #FD6E8A
  secondary-dark: b5b1aa #A2122F

# Footer settings
footer:
  copyright: Asheville Printmakers
  location: Our location 
  social: lonely social link
  credits: random fact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/avl_printmakers
  
# Postal address (add as many lines as necessary)
address:
  - line: Asheville &
  - line: Western North Carolina

# Credits content
credits: 'Hosted by Github Pages'

# Build settings
markdown: kramdown
permalink: pretty
